name: nick
age : 35
password: 3353113844
#等价于header :order
header: '{cipher}a75655901886ff98d697917ed299590aee53775d18274b6a558607f11eac0260'
# header: order



spring:
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
